# fly.toml app configuration file generated for qoud-ping-pong-tqk-6q on 2026-09-13T13:37:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qoud-ping-pong-tqk-6q'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '2567'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

 [experimental]
  entrypoint = ["pnpm", "start"]
 
